name: Build

on: workflow_dispatch

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/site-kit-wp'
      
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: '.nvmrc'
      
      - run: npm ci

  build_dev:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/site-kit-wp'
      
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - run: npm ci

  build_prod:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'google/site-kit-wp'
      
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: '.nvmrc'
      
      - run: npm ci
